### PR TITLE
Add support for TESTS_FAILED exit code

### PR DESCRIPTION
**Pull request by aahlborg**
Add support to suppress the TESTS_FAILED exit code.

Tested in Python 3.6 with pytest 4.6.5 and 5.0.1.

### CODE REVIEW

**Comment by yashtodi94** [comment]
Hey @aahlborg,

Thanks for coming up with this. Before merging it, may I ask what can be the possible use case for exiting with `OK` even if some tests are failing?

**Comment by aahlborg** [comment]
Jenkins will mark a build as FAILURE if any command returns a non-zero exit code. Returning 0 signals to Jenkins that the tests were able to run and the results can be evaluated using the XML test report instead.

**Comment by aahlborg** [comment]
I'm hoping this will solve my problem with running pytest in Jenkins:
https://stackoverflow.com/questions/57358519

My test setup contains a few buggy components so I don't want to suppress errors from segmentation faults, network errors, etc.

**Comment by yashtodi94** [comment]
Valid point. But there should be a log/print which says that failures are suppressed. This would hopefully prevent the `--suppress-tests-failed-exit-code` to be used as a hack where skipping failures is unintentional.

Can you make that change?

**Comment by aahlborg** [comment]
I don't know how to do this in a practical way. pytest_sessionfinish is called after tests have run but before output is printed for failed tests so it is not clearly visible in the output. Inserting a print("\nINFO: Tests failed but exit code was suppressed.") in this function yields:

> ====================== test session starts ======================
> platform win32 -- Python 3.6.8, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
> rootdir: C:\Work\pytest-custom_exit_code
> plugins: custom-exit-code-0.2.1
> collected 2 items
> 
> tests\test_custom_exit_code.py .F                                                                                [100%]
> INFO: Tests failed but exit code was suppressed.
> 
> 
> =========================== FAILURES ============================
> _______________________ test_tests_failed _______________________
> ...

**Comment by aahlborg** [comment]
I also don't see the need for this print. Installing pytest-custom-exit-code and supplying the --suppress-tests-failed-exit-code option is hardly unintentional.

**Comment by yashtodi94** [comment]
No problem. Will merge and release this and try adding a print at a later point. Thanks :)

**Pull request merged**
